language: python
python:
- '3.6'

before_install:
- openssl aes-256-cbc -K $encrypted_012b16b64e1a_key -iv $encrypted_012b16b64e1a_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

install:
- pip install -r requirements.txt
script:
- python app/manage.py test
